### ISSUE TITLE
DAC/ADC+ PRO

### ISSUE THREAD

**Issue by laenzlinger** [hifiberry/kicad_template_dac_adc_stage#1]
Can this project be used as base for DAC/ACD+ PRO projects? Are the header locations compatible?

**Comment by hifiberry** [comment]
No it can't be used for the DAC+ ADC Pro. This is a template for the DAC+ ADC Stage that's part of the development kit:
https://www.hifiberry.com/shop/0-development-kits/dac-adc-stage-development-kit/

The headers on the DAC+ ADC Pro are not designed for add-on cards. They might change with board revisions.
